# Generated by Django 4.1 on 2023-01-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="mytask.node",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Nodes", "ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[],
            options={
                "verbose_name_plural": "Categories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mytask.node",),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[],
            options={
                "verbose_name_plural": "sub categories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mytask.node",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mytask.subcategory",
                    ),
                ),
            ],
        ),
    ]
